# Generated by Django 3.2.6 on 2021-08-30 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_auto_20210826_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_color',
            field=models.CharField(choices=[('#FFFFFF', '白'), ('#CBFFD3', '黄緑'), ('#B1F9D0', '緑'), ('#EDFFBE', '黄色'), ('#C2EEFF', '水色'), ('#BAD3FF', '青'), ('#DCC2FF', '紫'), ('#FFBEDA', '赤'), ('#FFC7AF', 'オレンジ')], default=('#FFFFFF', '白'), max_length=100, verbose_name='色'),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True, max_length=2000, verbose_name='サイトのサムネイル'),
        ),
        migrations.AlterField(
            model_name='post',
            name='memo',
            field=models.TextField(blank=True, max_length=1000, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='site_url',
            field=models.URLField(max_length=1000, unique=True, verbose_name='サイトのURL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='myapp.Tag', verbose_name='タグ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
    ]
