# Generated by Django 3.2.6 on 2021-08-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='good',
            field=models.IntegerField(default=0),
        ),
    ]
