# Generated by Django 3.2.6 on 2021-08-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_tag_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='site_url',
            field=models.URLField(max_length=1000, verbose_name='サイトのURL'),
        ),
    ]
